"""
https://diia.gov.ua/

CSS Selectors
1. 'div.header_sign  >  a.btn_sign'
2. 'ul.menu_list li:first-child'
3. 'ul.menu_list li:nth-child(2)'
4. '.header_logo-diya'
5. '.nav-tabs li:last-child'
6. 'button ~ div[class^="form-search"]'
7. '.nav-link#biznesu-tab'
8. '.col-6 .wrap-all-link'
9. '.col-lg-6:last-child .row .col-6:nth-child(3)'
10. '.main-item_news-content'
11. '.question_section a[href$='faq']'
12. '.question_section .col-lg-4:nth-of-type(5)'
13. '[role="tabpanel"]:not(#biznesu) span:last-child'
14. '.tab-pane#gromadyanam .d-lg-block a'
15. '.store a:first-child'

XPATH
1. '//a[contains(@class, "btn_sign")]'
2. '//a[contains(text(), "Зареєструватися")]'
3. '//ul[@class = "menu_list"]/li[4]'
4. '//ul[@class = "menu_list"]/li[1]/a'
5. '//a[@class = "nav-link"]'
6. '//div[@id = "gromadyanam"]//div[contains(@class, "swiper_services-btn-next")]'
7. '//div[@id = "gromadyanam"]//div[contains(@class, "swiper_services-slide")][3]'
8. '//div[@id = "gromadyanam"]//span[6]'
9. '//div[@id="gromadyanam"]//div[@class="row"]//div[@class = "col-6"][last()]'
10. '//div[@id="gromadyanam"]//div[@class="row"][2]//div[@class = "col-6 col-lg-4"][last()]'
11. '//span[text()="Всі питання та відповіді"]'
12. '//span[text()="Всі питання та відповіді"]/parent::a'
13. '//span[text()="Всі питання та відповіді"]/ancestor::div[@class="wrap-all-link"]'
14. '//a[contains(text(), "Дізнатись більше")]'
15. '//div[@aria-labelledby="gromadyanam-tab"]//div[contains(@class , "d-none")]//a'
16. '//div[@class = "situations_head-title"]'
17. '//section[@class = "situations_section"]//div[@class = "col-lg-4"][1]//div[a]'
18. '//div[@class="main-item_news-preview"]'
19. '//div[@class="main-item_news-preview"]/parent::div//a'
20. '//div[@class="main-item_news-content-date"'
21. '//ul[contains(@class, "fa-white")]//child::li[last()]'
22. '//li[3]//a[@rel="nofollow"]'
23. '//a[@class="store-google"]'
24. '//a[@class="store-google"]//following-sibling::a'
25. '//a[@class="store-google"]//preceding-sibling::a'
26. '//div[@class="dev-company_icon"]/div[1]'
27. '//p[text()="2019 - 2022. Всі права захищені."]'
28. '//div[@class="row"]//li[@class="menu_footer-list-item"][2]'
29. '//nav[@class ="menu_footer"]//li[3]/a'
30. '//hr'
"""